import path from 'path';
import { Await } from '@component-controls/core';
import { runRelatedTests } from '../../../src';

let results: Await<ReturnType<typeof runRelatedTests>>;
beforeAll(async () => {
  results = await runRelatedTests(
    path.resolve(__dirname, '../../fixtures/story/VariantButton.tsx'),
  );
}, 100000);

describe('react story tests', () => {
  it('testResults ', () => {
    expect(results[0]).toMatchObject({
      testFileName: 'VariantButton.test.js',
      results: [
        {
          leaks: false,
          testFilePath: 'VariantButton.test.js',
          testResults: [
            {
              ancestorTitles: ['VariantButton', 'overview', '0'],
              fullName: 'VariantButton overview 0 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '0'],
              fullName: 'VariantButton overview 0 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '1'],
              fullName: 'VariantButton overview 1 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '1'],
              fullName: 'VariantButton overview 1 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '2'],
              fullName: 'VariantButton overview 2 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '2'],
              fullName: 'VariantButton overview 2 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '3'],
              fullName: 'VariantButton overview 3 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '3'],
              fullName: 'VariantButton overview 3 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '4'],
              fullName: 'VariantButton overview 4 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '4'],
              fullName: 'VariantButton overview 4 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '5'],
              fullName: 'VariantButton overview 5 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '5'],
              fullName: 'VariantButton overview 5 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '6'],
              fullName: 'VariantButton overview 6 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '6'],
              fullName: 'VariantButton overview 6 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '7'],
              fullName: 'VariantButton overview 7 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '7'],
              fullName: 'VariantButton overview 7 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '8'],
              fullName: 'VariantButton overview 8 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '8'],
              fullName: 'VariantButton overview 8 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '9'],
              fullName: 'VariantButton overview 9 snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'overview', '9'],
              fullName: 'VariantButton overview 9 accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'primary'],
              fullName: 'VariantButton primary snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'primary'],
              fullName: 'VariantButton primary accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'accent'],
              fullName: 'VariantButton accent snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'accent'],
              fullName: 'VariantButton accent accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'disabled'],
              fullName: 'VariantButton disabled snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'disabled'],
              fullName: 'VariantButton disabled accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'success'],
              fullName: 'VariantButton success snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'success'],
              fullName: 'VariantButton success accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'error'],
              fullName: 'VariantButton error snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'error'],
              fullName: 'VariantButton error accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'warning'],
              fullName: 'VariantButton warning snapshot',
              status: 'passed',
              title: 'snapshot',
              numPassingAsserts: 0,
              failureDetails: [],
            },
            {
              ancestorTitles: ['VariantButton', 'warning'],
              fullName: 'VariantButton warning accessibility',
              status: 'passed',
              title: 'accessibility',
              numPassingAsserts: 0,
              failureDetails: [],
            },
          ],
        },
      ],
      coverage: {
        '../../../dist/index.js': {
          lines: {
            total: 61,
            covered: 21,
            skipped: 0,
            pct: 34.43,
          },
          functions: {
            total: 15,
            covered: 1,
            skipped: 0,
            pct: 6.67,
          },
          statements: {
            total: 63,
            covered: 21,
            skipped: 0,
            pct: 33.33,
          },
          branches: {
            total: 16,
            covered: 4,
            skipped: 0,
            pct: 25,
          },
        },
        'VariantButton.docs.tsx': {
          lines: {
            total: 19,
            covered: 19,
            skipped: 0,
            pct: 100,
          },
          functions: {
            total: 7,
            covered: 7,
            skipped: 0,
            pct: 100,
          },
          statements: {
            total: 26,
            covered: 26,
            skipped: 0,
            pct: 100,
          },
          branches: {
            total: 0,
            covered: 0,
            skipped: 0,
            pct: 100,
          },
        },
        'VariantButton.tsx': {
          lines: {
            total: 10,
            covered: 10,
            skipped: 0,
            pct: 100,
          },
          functions: {
            total: 1,
            covered: 1,
            skipped: 0,
            pct: 100,
          },
          statements: {
            total: 11,
            covered: 11,
            skipped: 0,
            pct: 100,
          },
          branches: {
            total: 14,
            covered: 11,
            skipped: 0,
            pct: 78.57,
          },
        },
        'VariantButton.data.js': {
          lines: {
            total: 1,
            covered: 1,
            skipped: 0,
            pct: 100,
          },
          functions: {
            total: 0,
            covered: 0,
            skipped: 0,
            pct: 100,
          },
          statements: {
            total: 1,
            covered: 1,
            skipped: 0,
            pct: 100,
          },
          branches: {
            total: 0,
            covered: 0,
            skipped: 0,
            pct: 100,
          },
        },
      },
    });
  });
});
