export default {
  pagination: {
    '0': {
      totalCountVisible: false,
      totalCountTemplate: 'Dayne Effertz',
      pageIndex: 0,
      pageSize: 6,
      pageTemplate: 'Miss Judy Ullrich',
      pageVisible: false,
      pageSizeTemplate: 'Bridget Murazik',
      pageSizeVisible: true,
      goToPageVisible: false,
      goToPageTemplate: 'Jennings Sporer',
    },
    '1': {
      totalCountVisible: false,
      totalCountTemplate: 'Lonnie Strosin',
      pageIndex: 0,
      pageSize: 18,
      pageTemplate: 'Mia Schowalter II',
      pageVisible: true,
      pageSizeTemplate: 'Daisy Weissnat',
      pageSizeVisible: false,
      goToPageVisible: true,
      goToPageTemplate: 'Roy Cronin',
    },
    '2': {
      totalCountVisible: true,
      totalCountTemplate: 'Violette Buckridge',
      pageIndex: 0,
      pageSize: 14,
      pageTemplate: 'Myrtle Hartmann',
      pageVisible: true,
      pageSizeTemplate: 'Rahsaan Green',
      pageSizeVisible: false,
      goToPageVisible: true,
      goToPageTemplate: 'Dortha Vandervort',
    },
    '3': {
      totalCountVisible: true,
      totalCountTemplate: 'Terence Howe',
      pageIndex: 0,
      pageSize: 7,
      pageTemplate: 'Lorna Rice',
      pageVisible: true,
      pageSizeTemplate: 'Deron Koepp',
      pageSizeVisible: false,
      goToPageVisible: false,
      goToPageTemplate: 'Marty Considine',
    },
    '4': {
      totalCountVisible: true,
      totalCountTemplate: 'Cecile Witting',
      pageIndex: 0,
      pageSize: 10,
      pageTemplate: 'Tristin Hettinger Jr.',
      pageVisible: false,
      pageSizeTemplate: 'Frederique Ledner',
      pageSizeVisible: false,
      goToPageVisible: false,
      goToPageTemplate: 'Roselyn Kassulke',
    },
  },
};
