export default {
  pagination: {
    '0': {
      totalCountVisible: true,
      totalCountTemplate: 'Howell Williamson',
      pageIndex: 1,
      pageSize: 6,
      pageTemplate: 'Natasha Toy',
      pageVisible: false,
      pageSizeTemplate: 'Halle Ernser',
      pageSizeVisible: false,
      goToPageVisible: false,
      goToPageTemplate: 'Marian Connelly',
    },
    '1': {
      totalCountVisible: false,
      totalCountTemplate: 'Garfield Raynor',
      pageIndex: 0,
      pageSize: 8,
      pageTemplate: 'Alyce Kutch',
      pageVisible: false,
      pageSizeTemplate: 'Arnoldo Armstrong',
      pageSizeVisible: false,
      goToPageVisible: true,
      goToPageTemplate: 'Glennie Casper',
    },
    '2': {
      totalCountVisible: false,
      totalCountTemplate: 'Raymond Brown',
      pageIndex: 0,
      pageSize: 7,
      pageTemplate: 'Beth Jacobson',
      pageVisible: true,
      pageSizeTemplate: 'Chet Yundt',
      pageSizeVisible: true,
      goToPageVisible: false,
      goToPageTemplate: 'Dr. Bruce Howell',
    },
    '3': {
      totalCountVisible: false,
      totalCountTemplate: 'Rigoberto Rempel',
      pageIndex: 0,
      pageSize: 7,
      pageTemplate: 'Miss Maiya Glover',
      pageVisible: false,
      pageSizeTemplate: 'Annabell Luettgen IV',
      pageSizeVisible: false,
      goToPageVisible: false,
      goToPageTemplate: 'Dawson Glover',
    },
    '4': {
      totalCountVisible: false,
      totalCountTemplate: 'Dejon Lynch',
      pageIndex: 0,
      pageSize: 11,
      pageTemplate: 'Dr. Ryley Hills',
      pageVisible: true,
      pageSizeTemplate: 'Maximus Tillman',
      pageSizeVisible: true,
      goToPageVisible: false,
      goToPageTemplate: 'Bobbie Mante',
    },
  },
};
