export default {
  pagination: {
    '1': {
      header: true,
      sorting: true,
      filtering: false,
      itemsLabel: 'null',
      rowSelect: true,
      skipPageReset: false,
      pagination: 'boolean',
      slot: 'Ms. Alysha Daniel',
      title: 'Cleo Lindgren',
      key: 'null',
      defaultChecked: true,
      suppressContentEditableWarning: false,
      suppressHydrationWarning: true,
      accessKey: 'Ms. Ronny Mitchell',
      className: 'Jayce Schaden',
      contentEditable: 'Booleanish',
      contextMenu: 'Scot Kuhic',
      dir: 'Dr. Gustave Little',
      hidden: true,
      id: 'Jimmie Huel DVM',
      lang: 'Estella Wehner',
      placeholder: 'Columbus Ziemann',
      tabIndex: 0,
      radioGroup: 'Emmanuelle Wilderman',
      role: 'Mr. Laura Muller',
      about: 'Maxine Armstrong',
      datatype: 'Jairo Mraz',
      prefix: 'Carolyne Wunsch',
      property: 'Jefferey Haag',
      resource: 'Sidney Haley',
      typeof: 'Brenna Gleichner',
      vocab: 'Herman Bechtelar',
      autoCapitalize: 'Georgiana Ebert',
      autoCorrect: 'Katelynn Rowe',
      autoSave: 'Mr. Marielle Rogahn',
      color: '#19211e',
      itemProp: 'Elmo Dach',
      itemScope: true,
      itemType: 'Kathlyn Powlowski',
      itemID: 'Justice Boyer',
      itemRef: 'Grady Dibbert MD',
      results: 0,
      security: 'Grayce Flatley',
      unselectable: 'off',
      inputMode: 'email',
      is: 'Guillermo Nikolaus',
      'aria-activedescendant': 'Carolyne Larkin',
      'aria-atomic': 'false',
      'aria-autocomplete': 'none',
      'aria-busy': 'false',
      'aria-checked': 'true',
      'aria-colcount': 0,
      'aria-colindex': 1,
      'aria-colspan': 0,
      'aria-controls': 'Clemmie Lowe V',
      'aria-current': 'date',
      'aria-describedby': 'Tevin Botsford',
      'aria-details': 'Macy Kassulke',
      'aria-disabled': 'boolean',
      'aria-errormessage': 'Mr. Vladimir Conn',
      'aria-expanded': 'boolean',
      'aria-flowto': 'Aniya Corwin',
      'aria-haspopup': 'listbox',
      'aria-hidden': 'true',
      'aria-invalid': 'grammar',
      'aria-keyshortcuts': 'Abigale Gusikowski',
      'aria-label': 'Adella Nienow',
      'aria-labelledby': 'Ivah Lang MD',
      'aria-level': 1,
      'aria-live': 'off',
      'aria-modal': 'true',
      'aria-multiline': 'true',
      'aria-multiselectable': 'true',
      'aria-orientation': 'horizontal',
      'aria-owns': 'Tristian Smith',
      'aria-placeholder': 'Frederick Pfeffer',
      'aria-posinset': 0,
      'aria-pressed': 'boolean',
      'aria-readonly': 'false',
      'aria-relevant': 'text additions',
      'aria-required': 'false',
      'aria-roledescription': 'Miss Dudley Spinka',
      'aria-rowcount': 1,
      'aria-rowindex': 0,
      'aria-rowspan': 0,
      'aria-selected': 'false',
      'aria-setsize': 1,
      'aria-valuemax': 1,
      'aria-valuemin': 1,
      'aria-valuenow': 1,
      'aria-valuetext': 'Oswaldo Walsh',
      variant: 'Roxane Cormier MD',
      m: 'number',
      margin: 'number',
      mt: 'ResponsiveValue<string',
      marginTop: 'ResponsiveValue<string',
      mr: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginRight: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      mb: 'ResponsiveValue<string',
      marginBottom: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      ml: 'number',
      marginLeft: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      mx: 'number',
      marginX: 'ResponsiveValue<string',
      my: 'number',
      marginY: 'number',
      p: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      padding: 'number',
      pt: 'number',
      paddingTop: 'ResponsiveValue<string',
      pr: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingRight: 'ResponsiveValue<string',
      pb: 'ResponsiveValue<string',
      paddingBottom: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      pl: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingLeft: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      px: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingX: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      py: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingY: 'number',
      bg: 'ResponsiveValue<string',
      backgroundColor: 'number',
      totalCountVisible: false,
      totalCountTemplate: 'Keeley MacGyver',
      pageIndex: 1,
      pageSize: 11,
      pageTemplate: 'Esther Koch',
      pageVisible: false,
      pageSizeTemplate: 'Emelie Gerhold',
      pageSizeVisible: false,
      goToPageVisible: false,
      goToPageTemplate: 'Roxane Ritchie DVM',
    },
    '2': {
      header: false,
      sorting: false,
      filtering: false,
      itemsLabel: 'null',
      rowSelect: false,
      skipPageReset: true,
      pagination: 'boolean',
      slot: 'Randal Kub V',
      title: "Raleigh O'Hara",
      key: 'Key',
      defaultChecked: false,
      suppressContentEditableWarning: true,
      suppressHydrationWarning: false,
      accessKey: 'Fabiola Baumbach',
      className: 'Clementine Stehr',
      contentEditable: 'Booleanish',
      contextMenu: 'Cristopher Moore',
      dir: 'Amaya Buckridge',
      hidden: true,
      id: 'Vernice Reilly',
      lang: 'Mateo Dicki',
      placeholder: 'Mrs. Guy Tillman',
      tabIndex: 1,
      radioGroup: 'Joy Mayer',
      role: 'Delphia Lehner',
      about: 'Mohamed Renner',
      datatype: 'Jeramy Christiansen',
      prefix: 'Mekhi Brown',
      property: 'Carlee Lebsack',
      resource: 'Kaden Heaney',
      typeof: 'Lessie Lindgren MD',
      vocab: 'Dayne Effertz',
      autoCapitalize: 'Dolores Collins',
      autoCorrect: 'Cole Heaney PhD',
      autoSave: 'Gage Erdman',
      color: '#23711f',
      itemProp: 'Cornell Davis',
      itemScope: false,
      itemType: 'Shanna Schmidt',
      itemID: 'Beaulah MacGyver',
      itemRef: 'Rosario Crist',
      results: 1,
      security: 'Bernadine Anderson',
      inputMode: 'numeric',
      is: 'Jaclyn Zulauf',
      'aria-activedescendant': 'Elbert Cole',
      'aria-atomic': 'true',
      'aria-autocomplete': 'both',
      'aria-busy': 'true',
      'aria-checked': 'mixed',
      'aria-colcount': 1,
      'aria-colindex': 0,
      'aria-colspan': 0,
      'aria-controls': 'Erich Hammes',
      'aria-current': 'false',
      'aria-describedby': 'Stephen Boyle',
      'aria-details': 'Mr. Alba Thiel',
      'aria-disabled': 'boolean',
      'aria-errormessage': 'Kaycee Swaniawski',
      'aria-expanded': 'true',
      'aria-flowto': 'Austen Stark',
      'aria-haspopup': 'menu',
      'aria-hidden': 'true',
      'aria-invalid': 'spelling',
      'aria-keyshortcuts': 'Earnestine Greenholt',
      'aria-label': 'Mose Mosciski',
      'aria-labelledby': 'Sincere Mertz',
      'aria-level': 0,
      'aria-live': 'polite',
      'aria-modal': 'boolean',
      'aria-multiline': 'false',
      'aria-multiselectable': 'false',
      'aria-orientation': 'vertical',
      'aria-owns': 'Uriah Morar',
      'aria-placeholder': 'Jacynthe Hegmann',
      'aria-posinset': 0,
      'aria-pressed': 'boolean',
      'aria-readonly': 'true',
      'aria-required': 'true',
      'aria-roledescription': 'Mrs. Carmelo Osinski',
      'aria-rowcount': 1,
      'aria-rowindex': 0,
      'aria-rowspan': 0,
      'aria-selected': 'boolean',
      'aria-setsize': 1,
      'aria-sort': 'ascending',
      'aria-valuemax': 0,
      'aria-valuemin': 0,
      'aria-valuenow': 0,
      'aria-valuetext': 'Thea Gusikowski',
      variant: 'Carli Orn',
      m: 'number',
      margin: 'ResponsiveValue<string',
      mt: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginTop: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      mr: 'ResponsiveValue<string',
      marginRight: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      mb: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginBottom: 'ResponsiveValue<string',
      ml: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginLeft: 'ResponsiveValue<string',
      mx: 'number',
      marginX: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      my: 'ResponsiveValue<string',
      marginY: 'number',
      p: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      padding: 'ResponsiveValue<string',
      pt: 'ResponsiveValue<string',
      paddingTop: 'ResponsiveValue<string',
      pr: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingRight: 'ResponsiveValue<string',
      pb: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingBottom: 'ResponsiveValue<string',
      pl: 'ResponsiveValue<string',
      paddingLeft: 'ResponsiveValue<string',
      px: 'ResponsiveValue<string',
      paddingX: 'number',
      py: 'ResponsiveValue<string',
      paddingY: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      bg: 'ResponsiveValue<string',
      backgroundColor: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      totalCountVisible: false,
      totalCountTemplate: 'Donnell Purdy',
      pageIndex: 0,
      pageSize: 5,
      pageTemplate: 'Ms. Queen Goodwin',
      pageVisible: true,
      pageSizeTemplate: 'Owen Goldner',
      pageSizeVisible: true,
      goToPageVisible: false,
      goToPageTemplate: 'Junior Eichmann',
    },
    '3': {
      header: true,
      sorting: true,
      filtering: false,
      itemsLabel: 'null',
      rowSelect: false,
      skipPageReset: true,
      pagination: 'boolean',
      slot: 'Howell Bosco DDS',
      title: 'Adriana Littel',
      key: 'null',
      defaultChecked: true,
      suppressContentEditableWarning: false,
      suppressHydrationWarning: false,
      accessKey: 'Elissa Thiel',
      className: 'Mozell Fahey III',
      contentEditable: 'Booleanish',
      contextMenu: 'Gust Raynor',
      dir: 'Clinton Mills',
      hidden: true,
      id: 'German Pfeffer',
      lang: 'Kay Senger',
      placeholder: "Kara O'Connell",
      tabIndex: 1,
      translate: 'yes',
      radioGroup: 'Ms. Ezra Rolfson',
      role: 'Sanford Rolfson',
      about: 'Otis Skiles',
      datatype: 'Patrick Friesen',
      prefix: 'Minnie Boehm',
      property: 'Geovanny Thompson',
      resource: 'Jules Conroy',
      typeof: 'Samara Prohaska',
      vocab: 'Brycen Bins',
      autoCapitalize: 'Rico Dach',
      autoCorrect: 'Ofelia Shields',
      autoSave: 'Nona Hagenes',
      color: '#710f63',
      itemProp: 'Daisy Mertz',
      itemScope: true,
      itemType: 'Mr. Tessie Senger',
      itemID: 'Obie Boehm',
      itemRef: 'Pablo Parker V',
      results: 0,
      security: 'Theresia Brown',
      inputMode: 'url',
      is: 'Mr. Arturo Aufderhar',
      'aria-activedescendant': 'Ted Feil',
      'aria-atomic': 'boolean',
      'aria-autocomplete': 'list',
      'aria-busy': 'false',
      'aria-checked': 'mixed',
      'aria-colcount': 0,
      'aria-colindex': 0,
      'aria-colspan': 1,
      'aria-controls': 'Sasha Greenfelder',
      'aria-current': 'time',
      'aria-describedby': 'Hoyt Hartmann',
      'aria-details': 'Prince Barton III',
      'aria-disabled': 'false',
      'aria-errormessage': 'Felicia Nicolas PhD',
      'aria-expanded': 'false',
      'aria-flowto': 'Morgan Morissette',
      'aria-haspopup': 'true',
      'aria-hidden': 'boolean',
      'aria-invalid': 'boolean',
      'aria-keyshortcuts': 'Marielle Weber IV',
      'aria-label': 'Dr. Iva Gislason',
      'aria-labelledby': 'Leonardo Ankunding',
      'aria-level': 1,
      'aria-live': 'off',
      'aria-modal': 'true',
      'aria-multiline': 'true',
      'aria-multiselectable': 'true',
      'aria-orientation': 'horizontal',
      'aria-owns': 'Jamar Raynor',
      'aria-placeholder': 'Joshuah Stanton',
      'aria-posinset': 1,
      'aria-pressed': 'mixed',
      'aria-readonly': 'true',
      'aria-relevant': 'text',
      'aria-required': 'boolean',
      'aria-roledescription': 'Yesenia Willms',
      'aria-rowcount': 1,
      'aria-rowindex': 0,
      'aria-rowspan': 1,
      'aria-selected': 'boolean',
      'aria-setsize': 0,
      'aria-sort': 'none',
      'aria-valuemax': 1,
      'aria-valuemin': 0,
      'aria-valuenow': 0,
      'aria-valuetext': 'Kaelyn Toy',
      variant: 'Demond Bartell',
      m: 'ResponsiveValue<string',
      margin: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      mt: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginTop: 'ResponsiveValue<string',
      mr: 'number',
      marginRight: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      mb: 'number',
      marginBottom: 'ResponsiveValue<string',
      ml: 'number',
      marginLeft: 'ResponsiveValue<string',
      mx: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginX: 'ResponsiveValue<string',
      my: 'number',
      marginY: 'ResponsiveValue<string',
      p: 'number',
      padding: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      pt: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingTop: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      pr: 'number',
      paddingRight: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      pb: 'ResponsiveValue<string',
      paddingBottom: 'number',
      pl: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingLeft: 'ResponsiveValue<string',
      px: 'ResponsiveValue<string',
      paddingX: 'number',
      py: 'ResponsiveValue<string',
      paddingY: 'number',
      bg: 'number',
      backgroundColor: 'ResponsiveValue<string',
      totalCountVisible: true,
      totalCountTemplate: 'Lamont Beer',
      pageIndex: 0,
      pageSize: 14,
      pageTemplate: 'Angeline Moen',
      pageVisible: true,
      pageSizeTemplate: 'Mrs. Gabriel Morissette',
      pageSizeVisible: false,
      goToPageVisible: true,
      goToPageTemplate: 'Jovan Littel',
    },
    '4': {
      header: true,
      sorting: false,
      filtering: true,
      itemsLabel: 'string',
      rowSelect: true,
      skipPageReset: true,
      pagination: 'TablePaginationProps',
      slot: 'Katelynn Weber',
      title: 'Janae MacGyver',
      key: 'Key',
      defaultChecked: true,
      suppressContentEditableWarning: false,
      suppressHydrationWarning: true,
      accessKey: 'Prudence Kilback',
      className: 'Jerrell Littel',
      contentEditable: 'Booleanish',
      contextMenu: 'Audra Hagenes',
      dir: 'Sarah Cole',
      hidden: true,
      id: 'Jasen Considine',
      lang: 'Athena Jones',
      placeholder: 'Lamont Corkery',
      tabIndex: 1,
      translate: 'yes',
      radioGroup: 'Abdiel Morissette',
      role: 'Kristofer Stamm',
      about: 'Stone Dare',
      datatype: 'Georgette Bogisich',
      prefix: 'Thomas Hartmann',
      property: 'Mark Torphy',
      resource: 'Haskell Williamson',
      typeof: 'Davion Swaniawski',
      vocab: 'Dave Conroy',
      autoCapitalize: 'Mrs. Favian Hegmann',
      autoCorrect: 'Melyssa Watsica',
      autoSave: 'Nona Goldner',
      color: '#426621',
      itemProp: 'Manley Stanton',
      itemScope: false,
      itemType: 'Jany Turner',
      itemID: 'Rhiannon Batz DDS',
      itemRef: 'Adan McGlynn',
      results: 1,
      security: 'Mr. Mckenzie Rempel',
      inputMode: 'search',
      is: 'Jaydon Hyatt',
      'aria-activedescendant': 'Dr. Zackary Hilll',
      'aria-atomic': 'true',
      'aria-autocomplete': 'inline',
      'aria-busy': 'boolean',
      'aria-checked': 'mixed',
      'aria-colcount': 0,
      'aria-colindex': 0,
      'aria-colspan': 0,
      'aria-controls': 'Pat Parker',
      'aria-current': 'true',
      'aria-describedby': 'Chaz Lang',
      'aria-details': 'Alex Cassin',
      'aria-disabled': 'true',
      'aria-errormessage': 'Nash Harris',
      'aria-expanded': 'false',
      'aria-flowto': 'Imani Murphy',
      'aria-haspopup': 'false',
      'aria-hidden': 'true',
      'aria-invalid': 'false',
      'aria-keyshortcuts': 'Jennyfer Becker',
      'aria-label': 'Carmel Gleason IV',
      'aria-labelledby': 'Price Beer',
      'aria-level': 1,
      'aria-live': 'off',
      'aria-modal': 'boolean',
      'aria-multiline': 'boolean',
      'aria-multiselectable': 'false',
      'aria-owns': 'Pascale Bednar IV',
      'aria-placeholder': 'Jadon Volkman',
      'aria-posinset': 0,
      'aria-pressed': 'mixed',
      'aria-readonly': 'false',
      'aria-relevant': 'all',
      'aria-required': 'true',
      'aria-roledescription': 'Cornelius Rath',
      'aria-rowcount': 1,
      'aria-rowindex': 0,
      'aria-rowspan': 1,
      'aria-selected': 'true',
      'aria-setsize': 0,
      'aria-sort': 'other',
      'aria-valuemax': 1,
      'aria-valuemin': 0,
      'aria-valuenow': 1,
      'aria-valuetext': 'June Olson',
      variant: 'Bettye Greenholt',
      m: 'ResponsiveValue<string',
      margin: 'ResponsiveValue<string',
      mt: 'number',
      marginTop: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      mr: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginRight: 'number',
      mb: 'ResponsiveValue<string',
      marginBottom: 'number',
      ml: 'ResponsiveValue<string',
      marginLeft: 'ResponsiveValue<string',
      mx: 'number',
      marginX: 'number',
      my: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginY: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      p: 'ResponsiveValue<string',
      padding: 'ResponsiveValue<string',
      pt: 'number',
      paddingTop: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      pr: 'number',
      paddingRight: 'ResponsiveValue<string',
      pb: 'ResponsiveValue<string',
      paddingBottom: 'ResponsiveValue<string',
      pl: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingLeft: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      px: 'ResponsiveValue<string',
      paddingX: 'number',
      py: 'ResponsiveValue<string',
      paddingY: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      bg: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      backgroundColor: 'ResponsiveValue<string',
      totalCountVisible: false,
      totalCountTemplate: 'Dr. Stacey Batz',
      pageIndex: 0,
      pageSize: 14,
      pageTemplate: 'Johnathon Koch',
      pageVisible: true,
      pageSizeTemplate: 'Jacques Effertz',
      pageSizeVisible: false,
      goToPageVisible: true,
      goToPageTemplate: 'Ebba Marks',
    },
    '5': {
      header: true,
      sorting: true,
      filtering: false,
      itemsLabel: 'null',
      rowSelect: true,
      skipPageReset: true,
      pagination: 'TablePaginationProps',
      slot: 'Branson Connelly DDS',
      title: 'Hassie Bashirian',
      key: 'null',
      defaultChecked: true,
      suppressContentEditableWarning: false,
      suppressHydrationWarning: true,
      accessKey: 'Genesis Kerluke',
      className: 'Ignatius Grimes',
      contentEditable: 'inherit',
      contextMenu: 'Eleanore Johns',
      dir: 'Hunter Bauch',
      hidden: true,
      id: 'Kaleigh Jenkins',
      lang: 'Imani Johnson',
      placeholder: 'Brenden Conn',
      tabIndex: 1,
      translate: 'no',
      radioGroup: 'Orville Kreiger',
      role: 'Edward Steuber',
      about: 'Litzy Kassulke',
      datatype: 'Kaya Baumbach',
      prefix: "Roman O'Kon",
      property: 'Myrtle Greenholt',
      resource: 'Rahsaan Schmeler',
      typeof: 'Kaylin Batz',
      vocab: 'Ulises Ryan',
      autoCapitalize: 'Isabel Crist',
      autoCorrect: 'Eddie Barrows',
      autoSave: 'Liza Tromp',
      color: '#755b7c',
      itemProp: 'Mr. Jarret Padberg',
      itemScope: false,
      itemType: 'Conrad Schmidt',
      itemID: 'Alessandra Crona',
      itemRef: 'Darryl Hartmann MD',
      results: 0,
      security: 'Warren Dickens',
      inputMode: 'email',
      is: 'Estevan Green',
      'aria-activedescendant': 'Mr. Abelardo Champlin',
      'aria-atomic': 'false',
      'aria-autocomplete': 'list',
      'aria-busy': 'boolean',
      'aria-checked': 'mixed',
      'aria-colcount': 1,
      'aria-colindex': 1,
      'aria-colspan': 1,
      'aria-controls': 'Johnathan McKenzie',
      'aria-current': 'time',
      'aria-describedby': 'Dorothea Mosciski',
      'aria-details': "Gordon O'Conner",
      'aria-disabled': 'false',
      'aria-errormessage': 'Coy Ruecker',
      'aria-expanded': 'false',
      'aria-flowto': 'Linnea Pouros',
      'aria-haspopup': 'boolean',
      'aria-hidden': 'true',
      'aria-invalid': 'false',
      'aria-keyshortcuts': 'Jeffery Wisoky I',
      'aria-label': 'Jedidiah Gerhold',
      'aria-labelledby': 'Elinor Kertzmann',
      'aria-level': 1,
      'aria-live': 'assertive',
      'aria-modal': 'false',
      'aria-multiline': 'true',
      'aria-multiselectable': 'true',
      'aria-orientation': 'vertical',
      'aria-owns': 'Mr. Elouise Waters',
      'aria-placeholder': 'Marcus Jacobi',
      'aria-posinset': 0,
      'aria-pressed': 'boolean',
      'aria-readonly': 'boolean',
      'aria-relevant': 'additions removals',
      'aria-required': 'true',
      'aria-roledescription': 'Pearlie Collins',
      'aria-rowcount': 1,
      'aria-rowindex': 1,
      'aria-rowspan': 0,
      'aria-selected': 'boolean',
      'aria-setsize': 1,
      'aria-sort': 'none',
      'aria-valuemax': 0,
      'aria-valuemin': 1,
      'aria-valuenow': 1,
      'aria-valuetext': 'Audreanne Lakin',
      variant: 'Hector Conn',
      m: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      margin: 'ResponsiveValue<string',
      mt: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginTop: 'number',
      mr: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      marginRight: 'number',
      mb: 'number',
      marginBottom: 'number',
      ml: 'number',
      marginLeft: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      mx: 'number',
      marginX: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      my: 'number',
      marginY: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      p: 'ResponsiveValue<string',
      padding: 'number',
      pt: 'ResponsiveValue<string',
      paddingTop: 'ResponsiveValue<string',
      pr: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingRight: 'ResponsiveValue<string',
      pb: 'ResponsiveValue<string',
      paddingBottom: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      pl: 'number',
      paddingLeft: 'number',
      px: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      paddingX: 'number',
      py: 'number',
      paddingY: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      bg: 'ResponsiveValue<string',
      backgroundColor: 'symbol, Required<Theme<TLengthStyledSystem>>>',
      totalCountVisible: false,
      totalCountTemplate: 'Gerald Donnelly V',
      pageIndex: 0,
      pageSize: 7,
      pageTemplate: 'Mr. Hester Abbott',
      pageVisible: false,
      pageSizeTemplate: 'Daryl Gottlieb',
      pageSizeVisible: false,
      goToPageVisible: false,
      goToPageTemplate: 'Ebba McLaughlin',
    },
  },
};
